version: "3"
services:
  api:
    build: .
    container_name: api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    working_dir: /usr/src/fastfood
    command: bash -c "npx prisma migrate dev && npx prisma db seed && npm run start"
    restart: unless-stopped
    env_file: 
      - ./.env
  postgres:
    image: postgres:13-alpine
    env_file: 
      - ./.env
    volumes:
      - /usr/local/fastfood-pg/data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /usr/source/fastfood/front-end:/var/www/html
 
