on:
  push:
    branches:
      - main
jobs:
  pullRequestTest:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: generate .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
         envkey_PORT: ${{ secrets.PORT }}
         envkey_DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER}}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/fastfood
         envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
         envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
         envkey_POSTGRES_DB: fastfood
         directory: .
         file-name: .env

      - name: Build
        run: docker-compose build

      - name: run  
        run: docker compose down && docker compose up -d

  
      

